### ISSUE TITLE
Investigate main builds failing

### ISSUE THREAD

**Issue by ciaransweet** [pangeo-forge/pangeo-forge-aws-bakery#5]
For some reason, the `main` branch is failing to run its GitHub Actions, it's failing on the `Install root dependencies` step, even though the same step in the PR it was derived from passed fine.

This is the latest run of the PR: https://github.com/pangeo-forge/pangeo-forge-aws-bakery/actions/runs/647123452

We then merged the PR.

Then we get this on `main`: https://github.com/pangeo-forge/pangeo-forge-aws-bakery/actions/runs/647281059

```
Creating a virtualenv for this project...
Pipfile: /home/runner/work/pangeo-forge-aws-bakery/pangeo-forge-aws-bakery/Pipfile
Using /opt/hostedtoolcache/Python/3.8.8/x64/bin/python3.8 (3.8.8) to create virtualenv...
created virtual environment CPython3.8.8.final.0-64 in 569ms
  creator CPython3Posix(dest=/home/runner/.local/share/virtualenvs/pangeo-forge-aws-bakery-B3uWvNTt, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, wheel=bundle, setuptools=bundle, via=copy, app_data_dir=/home/runner/.local/share/virtualenv)
    added seed packages: pip==21.0.1, setuptools==52.0.0, wheel==0.36.2
  activators PythonActivator,FishActivator,XonshActivator,CShellActivator,PowerShellActivator,BashActivator


Successfully created virtual environment!
Virtualenv location: /home/runner/.local/share/virtualenvs/pangeo-forge-aws-bakery-B3uWvNTt
Pipfile.lock (b68491) out of date, updating to (fe2d7c)...
Locking [dev-packages] dependencies...

Building requirements...

Resolving dependencies...

FAIL
ERROR:pip.subprocessor:Command errored out with exit status 1:
 command: /home/runner/.local/share/virtualenvs/pangeo-forge-aws-bakery-B3uWvNTt/bin/python /usr/local/lib/python2.7/dist-packages/pipenv/patched/notpip install --ignore-installed --no-user --prefix /tmp/pip-build-env-onbterpb/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=41.0' setuptools-scm wheel
     cwd: None
Complete output (18 lines):
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/notpip/__main__.py", line 18, in <module>
    from pipenv.patched.notpip._internal.cli.main import main as _main  # isort:skip # noqa
  File "/usr/local/lib/python2.7/dist-packages/pipenv/__init__.py", line 23, in <module>
    from pipenv.vendor.vistir.compat import ResourceWarning, fs_str
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/vistir/__init__.py", line 4, in <module>
    from .compat import (
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/vistir/compat.py", line 202, in <module>
    IS_TYPE_CHECKING = os.environ.get("MYPY_RUNNING", is_type_checking())
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/vistir/compat.py", line 196, in is_type_checking
    from typing import TYPE_CHECKING
  File "/usr/local/lib/python2.7/dist-packages/typing.py", line 782, in <module>
    AnyStr = TypeVar('AnyStr', bytes, unicode)
NameError: name 'unicode' is not defined
----------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pipenv/resolver.py", line 764, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/resolver.py", line 758, in main
    _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system, parsed.write,
  File "/usr/local/lib/python2.7/dist-packages/pipenv/resolver.py", line 741, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/resolver.py", line 702, in resolve_packages
    results, resolver = resolve(
  File "/usr/local/lib/python2.7/dist-packages/pipenv/resolver.py", line 684, in resolve
    return resolve_deps(
  File "/usr/local/lib/python2.7/dist-packages/pipenv/utils.py", line 1395, in resolve_deps
    results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
  File "/usr/local/lib/python2.7/dist-packages/pipenv/utils.py", line 1108, in actually_resolve_deps
    resolver.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/utils.py", line 823, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/resolver.py", line 180, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/resolver.py", line 268, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/resolver.py", line 383, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/repositories/pypi.py", line 229, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/repositories/pypi.py", line 350, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/repositories/pypi.py", line 306, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/notpip/_internal/legacy_resolve.py", line 339, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/notpip/_internal/legacy_resolve.py", line 287, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
    abstract_dist = _get_prepared_distribution(
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 95, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/notpip/_internal/distributions/sdist.py", line 38, in prepare_distribution_metadata
    self._setup_isolation(finder)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/notpip/_internal/distributions/sdist.py", line 66, in _setup_isolation
    self.req.build_env.install_requirements(
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/notpip/_internal/build_env.py", line 202, in install_requirements
    call_subprocess(args, spinner=spinner)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/notpip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pipenv.patched.notpip._internal.exceptions.InstallationError: Command errored out with exit status 1: /home/runner/.local/share/virtualenvs/pangeo-forge-aws-bakery-B3uWvNTt/bin/python /usr/local/lib/python2.7/dist-packages/pipenv/patched/notpip install --ignore-installed --no-user --prefix /tmp/pip-build-env-onbterpb/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=41.0' setuptools-scm wheel Check the logs for full command output.


Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pipenv/utils.py", line 1131, in create_spinner
    yield sp
  File "/usr/local/lib/python2.7/dist-packages/pipenv/utils.py", line 1338, in venv_resolve_deps
    c = resolve(cmd, sp)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/utils.py", line 1176, in resolve
    sys.exit(c.return_code)
SystemExit: 1
```

It might be a red herring, but GitHub is warning:

```
Ubuntu-latest workflows will use Ubuntu-20.04 soon. For more details, see https://github.com/actions/virtual-environments/issues/1816
```

But I don't think this should affect it.

**Comment by ciaransweet** [comment]
Now I'm looking at `pyenv`, it doesn't have `3.8.8` yet so I can't install it with `pyenv` locally to see if it's `3.8.8` or the OS.

Though with it working on one branch and not the other, I'd hazard that it's the OS.

**Comment by ciaransweet** [comment]
Ah, looking at https://github.com/actions/virtual-environments/issues/1816

```
Known issues:

    * libcurl3 missing in the repo, replaced with libcurl4
    * Python2 is absent on Ubuntu 20, but required for some packages to install. Can be installed via apt-get install
    python-is-python2 or via toolcache
    * Python2 pip should be installed separately(curl https://bootstrap.pypa.io/get-pip.py --output get-pip.py, python2 get-pip.py)
    * Ansible should be installed from the official Ubuntu repo, ppa:ansible/ansible isn't updated yet
    * Set condition in git-lfs installation (Ubuntu 18 & 20 can install git-lfs from Ubuntu repo)
    * Android SDK should be pointed to Java8 explicitly
```

Looks like the lack of Python 2 might be the cause, I'll raise a PR adding these steps and see if that works.

**Comment by ciaransweet** [comment]
Fixed by pinning both our Pipfile and CI Machine versions https://github.com/pangeo-forge/pangeo-forge-aws-bakery/pull/7
